server:
  port: 8091

spring:
  application:
    name: doctor-module
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/doctor_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    loadbalancer:
      health-check:
        refetch-instances: true
        refetch-instances-interval: 1s
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true


